In [1]:
! pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.5.18.1)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [1]:
! mkdir ~/.kaggle

In [2]:
! cp kaggle.json ~/.kaggle/

In [3]:
! chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle datasets download -d fedesoriano/heart-failure-prediction

Downloading heart-failure-prediction.zip to /content
  0% 0.00/8.56k [00:00<?, ?B/s]
100% 8.56k/8.56k [00:00<00:00, 6.59MB/s]

In [5]:
! unzip heart-failure-prediction.zip

Archive:  heart-failure-prediction.zip
  inflating: heart.csv

In [6]:
import pandas as pd

df=pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [7]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [20]:
df.shape

(918, 12)

Checking features that have outliers

In [21]:
df1 = df[df.Cholesterol<=(df.Cholesterol.mean()+3*df.Cholesterol.std())]
df1.shape

(915, 12)

MaxHR and FastingBS doesn't have outliers

In [57]:
df[df.MaxHR>(df.MaxHR.mean()+3*df.MaxHR.std())]

In [23]:
df[df.FastingBS>(df.FastingBS.mean()+3*df.FastingBS.std())]

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [24]:
df[df.Oldpeak>(df.Oldpeak.mean()+3*df.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,1,0,140,231,0,2,140,1,5.0,1,1
702,59,1,3,178,270,0,0,145,0,4.2,0,0
771,55,1,0,140,217,0,1,111,1,5.6,0,1
791,51,1,0,140,298,0,1,122,1,4.2,1,1
850,62,0,0,160,164,0,0,145,0,6.2,0,1
900,58,1,0,114,318,0,2,140,0,4.4,0,1

In [25]:
df2 = df1[df1.Oldpeak<=(df1.Oldpeak.mean()+3*df1.Oldpeak.std())]
df2.shape

(909, 12)

In [26]:
df[df.RestingBP>(df.RestingBP.mean()+3*df.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,1,1,190,241,0,1,106,0,0.0,2,0
241,54,1,0,200,198,0,1,142,1,2.0,1,1
365,64,0,0,200,0,0,1,140,1,1.0,1,1
399,61,1,2,200,0,1,2,70,0,0.0,1,1
592,61,1,0,190,287,1,0,150,1,2.0,0,1
732,56,0,0,200,288,1,0,133,1,4.0,0,1
759,54,1,1,192,283,0,0,195,0,0.0,2,1

In [27]:
df3 = df2[df2.RestingBP<=(df2.RestingBP.mean()+3*df2.RestingBP.std())]
df3.shape

(902, 12)

In [30]:
df4 = df3.copy()
df4.ExerciseAngina.replace(
    {
        'N': 0,
        'Y': 1
    },
    inplace=True)

df4.ST_Slope.replace(
    {
        'Down': 1,
        'Flat': 2,
        'Up': 3
    },
    inplace=True
)

df4.RestingECG.replace(
    {
        'Normal': 1,
        'ST': 2,
        'LVH': 3
    },
    inplace=True)

df4.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [31]:
df5 = pd.get_dummies(df4, drop_first=True)
df5.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0

In [32]:
X=df5.drop('HeartDisease',axis='columns').values
y=df5.HeartDisease

In [34]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.42896269,  0.51485643,  0.22498958, ..., -0.82065181,
        -0.84676261,  1.0456339 ],
       [-0.47545956, -1.94228905,  1.27107517, ..., -0.82065181,
         0.14079864, -0.62072967],
       [-1.74679706,  0.51485643,  0.22498958, ..., -0.82065181,
        -0.84676261,  1.0456339 ],
       ...,
       [ 0.37209878,  0.51485643, -0.82109601, ...,  1.21854359,
         0.33831089, -0.62072967],
       [ 0.37209878, -1.94228905,  0.22498958, ..., -0.82065181,
        -0.84676261, -0.62072967],
       [-1.64085227,  0.51485643,  1.27107517, ..., -0.82065181,
        -0.84676261,  1.0456339 ]])

Use PCA to reduce dimensions

Use components such that 95% of variance is retained

In [40]:
from sklearn.decomposition import PCA

pca=PCA(0.95)
X_pca=pca.fit_transform(X_scaled)
X_pca.shape

(902, 10)

In [41]:
pca.explained_variance_ratio_

array([0.25347082, 0.13152653, 0.10502702, 0.09229999, 0.07945004,
       0.0775971 , 0.072906  , 0.05472823, 0.05038383, 0.04496732])

In [42]:
pca.n_components_

10

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_pca,y,test_size=0.3,random_state=30)

In [50]:
X_train.shape

(631, 10)

In [51]:
X_test.shape

(271, 10)

In [44]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [45]:
from sklearn.model_selection import GridSearchCV

In [46]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X_train, Y_train)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

                 model  best_score                best_params
0                  svm    0.868404  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.839908       {'n_estimators': 10}
2  logistic_regression    0.838308                   {'C': 1}

In [47]:
model=svm.SVC(C=1,kernel='rbf',gamma='auto')

In [48]:
model.fit(X_train,Y_train)

SVC(C=1, gamma='auto')

In [49]:
model.score(X_test,Y_test)

0.8745387453874539